#!/bin/sh

# this is script wraps the original binary application,
# and sets the library paths just before launching

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/kicad.app/Contents/MacOS

export KICAD_APP=$DIR/../../../kicad.app
export KICAD_DATA=$DIR/../../../data
export KICAD_PATH=$KICAD_DATA

# let the apps find the libraries at startup
export DYLD_LIBRARY_PATH=$KICAD_APP/Contents/Frameworks:$DYLD_LIBRARY_PATH

# let python scripting find our modules
export PYTHONPATH=$KICAD_APP/Contents/Frameworks/python2.7/site-packages/:$PYTHONPATH

export KICAD=$KICAD_DATA

# fallback to the available python binary

PY27=`which python2.7`
PY26=`which python2.6`
PY25=`which python2.5`


if [ -e "$PY27" ]; then
	$PY27 $*
	exit $#
fi

if [ -e "$PY26" ]; then
	$PY26 $*
	exit $#
fi


if [ -e "$PY25" ]; then
	$PY25 $*
	exit $#
fi


